<a href="https://colab.research.google.com/github/tdiya99-creator/GLA-Bootcamp/blob/main/b2_session4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# first code snippet

marks =[78,63,62]
avg=sum(marks)/len(marks)
print(avg)

67.66666666666667


In [ ]:
#second code snipptt
def calculate_average(marks):
  return sum(marks)/len(marks)
marks=[78,63,62]
print(calculate_average(marks))

67.66666666666667


In [ ]:
#reusability
#parameters
#write a simple function (reusable) to filter students pass or fail based on the condition: that the students gets 27

def check_result(marks):
    if marks >= 27:
        return "Pass"
    else:
        return "Fail"
students = [45, 20, 27, 10, 35]
for mark in students:
    print(mark, ":", check_result(mark))

45 : Pass
20 : Fail
27 : Pass
10 : Fail
35 : Pass


In [ ]:
def get_result_status(score):
  if score >= 27:
    return "Pass"
  return "Fail"

print(get_result_status(85))
print(get_result_status(32))


Pass
Pass


In [ ]:
#python list
"""general purpose
can hold any data types or mixed data types
normal programming
oprations need loops"""


'general purpose\ncan hold any data types or mixed data types\nnormal programming\noprations need loops'

In [ ]:
#numpy array
"""numerical data focused
usually holds one main numeric type
mathematical operations
operations can apply to the whole array"""


'numerical data focused\nusually holds one main numeric type\nmathematical operations\noperations can apply to the whole array'

In [ ]:
marks =[78,63,62]
# print(marks+10) # This line caused the TypeError


In [ ]:
import numpy as np

marks_array=np.array([78,63,62])
print(marks_array+10)

[88 73 72]


In [ ]:
#shape: the structure of array
#index: the position of an element
#axis: direction of the calculation across rows or columns or XYZ axis

In [ ]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)

matrix=np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
grid=np.array([
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45],
    [51,52,53,54,55]
])
print(grid[0,0])
print(grid[0])
print(grid[:0])
print(grid[:,0])
print(grid[0:3, 0:3])
print(grid[1:4, 1:4])

11
[11 12 13 14 15]
[]
[11 21 31 41 51]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [ ]:
marks= np.array([78,91,55,72,40,88])
print(marks>70)

high_scores=marks[marks>70]
print(high_scores)

[ True  True False  True False  True]
[78 91 72 88]


In [ ]:
marks=np.array([78,91,55,72,40,88])

print(marks.mean())
print(marks.min())
print(marks.max())
print(marks.sum())

70.66666666666667
40
91
424


In [ ]:
#find the class average
#find the highest score
#find the lowest high scores
#count students above 75

In [ ]:
import numpy as np
marks =np.array([78, 91, 55, 72, 40,
                 88,98,81,11,23,78,88,
                 91,96])
average = np.mean(marks)
highest_score = np.max(marks)
lowest_score = np.min(marks)
high_scores_count = np.sum(marks > 75)
print("Class Average:", average)
print("Highest Score:", highest_score)
print("Lowest Score:", lowest_score)
print("Number of Students above 75:", high_scores_count)

Class Average: 70.71428571428571
Highest Score: 98
Lowest Score: 11
Number of Students above 75: 9


In [1]:
from google.colab import files
uploaded=files.upload()

Saving session4_dummy_students_data.csv.xlsx to session4_dummy_students_data.csv.xlsx


In [4]:
import pandas as pd

df=pd.read_excel("session4_dummy_students_data.csv.xlsx")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [5]:
df["average"]=df[["math","science","english"]].mean(axis=1)
print(df[["name","math","science","english","average"]])

      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667


In [6]:
math_scores=df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [7]:
#calculate the average score across the other two subjects
#filtering
#top students average more than or equal to 85

df["average"]=df[["math","science","english"]].mean(axis=1)
print(df[["name","math","science","english","average"]])

top_students =df[df["average"]>=85]
print(top_students[["name","average"]])

#low attendance, if the attendance percentage is less than 75 then
#mathura students, name, city, average

low_attendance=df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])


      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667
      name    average
1     Diya  

In [8]:
#low attendance, if the attendance percentage is less than 75 then
low_attendance=df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66


In [9]:
#mathura students

mathura_students = df[df["city"]=="Mathura"]
print(mathura_students[["name", "city", "average"]])

      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000


In [10]:
#STUDENT PERFORMANCE ANALYSER

"""● Read session4_dumny_students.csv.
● Create an average column using math, science, and english.
● Create a result column: Pass if average > 40, otherwise Fail.
● Print class average.
● Print highest average and lowest average subject wise.
● Print top student or students.
● Print students with attendance below 75.
● Print students who submitted fewer than 6 assignments.
● Save final output as session4_student report.csv."""

'● Read session4_dumny_students.csv.\n● Create an average column using math, science, and english.\n● Create a result column: Pass if average > 40, otherwise Fail.\n● Print class average.\n● Print highest average and lowest average subject wise.\n● Print top student or students.\n● Print students with attendance below 75.\n● Print students who submitted fewer than 6 assignments.\n● Save final output as session4_student report.csv.'

In [12]:
import pandas as pd
import numpy as np

def get_result(avg):
  if avg>=40:
    return "Pass"
  return "Fail"

df = pd.read_excel("session4_dummy_students_data.csv.xlsx")

df["average"] = df[["math","science","english"]].mean(axis=1)
df["result"] = df["average"].apply(get_result)

print("Full_Data:")
print(df)

print("class average:",df["average"].mean())
print("Highest average:",df["average"].max())
print("Lowest average:",df["average"].min())

low_assignment_student = df[df["assignments_submitted"] < 6]
print("Students with fewer than 6 assignments:")
print(low_assignment_student[["name", "assignments_submitted"]])

Full_Data:
    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  